# You can find the default config with description of parameters here:
# https://github.com/arboriginal/SCT-PapiPositionTracker/blob/master/src/settings.yml
#
# Permissions for this tracker are listed here:
# https://github.com/arboriginal/SCT-PapiPositionTracker/blob/master/README.md#permissions
#
# Example of positions:
#
# positions:
#   arboriginal: # Example of position of a player (require "otherplayer" addon for PlaceholderAPI)
#     x: "%otherplayer_locx_arboriginal%"
#     z: "%otherplayer_locz_arboriginal%"
#
#   bed: # Example of position of player's bed (require "player" addon for PlaceholderAPI)
#     x: "%player_bed_x%"
#     z: "%player_bed_z%"

positions: {} # Names positions players can track, see example below ("{}" represents an empty list).

settings:
  check_update: true # If true, when you (re)load the plugin, it try to check if a new version is available
  autoload_target: false # If true, permissions "scompass.track.auto.PAPI_POSITION.<name>" are activated
  inactive_target: false # If true, inactive targets will be added to compasses too (can affect performances and disturb display)

  symbol: "§6♅" # Symbol displayed on the compass to represent this kind of trackers positions.
  temp:   "☧"   # Advanced: Symbol temporary used by the plugin, must be unique, 1 char and not used in "symbol".

  auto_disabled: 5 # If player closer than this (in blocks) from the target, the tracking stop automatically (0 to disable).

  limits:
    START: 2 # Number of maximum simultaneous positions a player (from this tracker) can track

  # Require settings.inactive_target: true
  inactive_symbol: "§7♅" # Symbol displayed on the compass to represent inactive targets of this kind of trackers positions.
  inactive_temp:   "☲"   # Advanced: Symbol temporary used by the plugin, must be unique, 1 char and not used in "symbol" nor "inactive_symbol".

  # Those parameters are used to highlight active targets when you facing them
  hl_angle: 0      # Angle in degree (integer) centered on compass middle point to be considered as faced (for example 30 means from 60° to 120°)
  hl_symbol: "§b♅" # Symbol displayed on the compass to represent active targets you are facing (require hl_angle > 0)
  hl_temp: "♵"     # Advanced: Symbol temporary used by the plugin (only used when hl_angle > 0)

locales:
  en:
    name: "papi" # Only use alphabetic and numeric values, not space

    list: "{prefix}&rNamed positions: {list}."
    list_empty: "{prefix}&rNo named positions."

    ADD: "{prefix}&aNamed position &e{target}&a has been created."
    DEL: "{prefix}&aNamed position &e{target}&a has been deleted."
    START: "{prefix}&6You are now tracking &e{target}&6 position."
    STOP: "{prefix}&6You no longer track &e{target}&6 position."

    help:
      noargs: |
        &r- &c/{command} &e{tracker}
        &7  Show list of trackable positions.
      ADD: |
        &r- &c/{command} &e{tracker} &6{ADD} &3<name> &b<x> <z>
        &7  Create a new trackable position.
      DEL: |
        &r- &c/{command} &e{tracker} &6{DEL} &3<name>
        &7  Remove this trackable position.
      START: |
        &r- &c/{command} &e{tracker} &6{START} &3<name>
        &7  Begin the tracking of this named position.
      STOP: |
        &r- &c/{command} &e{tracker} &6{STOP} &3<name>
        &7  End the tracking of this named position.

    target_auto_disabled: "{prefix}&3You've reached &b{target}&3, tracking disabled in &b{tracker}&3 tracker."

  fr:
    name: "papi" # N'utilise que des chiffres et des lettres, pas d'espace

    list: "{prefix}&rPositions nommées : {list}."
    list_empty: "{prefix}&rAucune position nommée."

    ADD: "{prefix}&aLa position &e{target}&a a été créée."
    DEL: "{prefix}&aLa position &e{target}&a a été supprimée."
    START: "{prefix}&6Tu pistes maintenant la position &e{target}&6."
    STOP: "{prefix}&6Tu ne pistes plus la position &e{target}&6."

    help:
      noargs: |
        &r- &c/{command} &e{tracker}
        &7  Affiche la liste des positions nommées.
      ADD: |
        &r- &c/{command} &e{tracker} &6{ADD} &3<nom> &b<x> <z>
        &7  Crée une position nommée.
      DEL: |
        &r- &c/{command} &e{tracker} &6{DEL} &3<nom>
        &7  Supprime une position nommée.
      START: |
        &r- &c/{command} &e{tracker} &6{START} &3<nom>
        &7  Démarre le pistage d'une position nommée.
      STOP: |
        &r- &c/{command} &e{tracker} &6{STOP} &3<nom>
        &7  Arrête le pistage d'une position nommée.

    target_auto_disabled: "{prefix}&3Tu as atteint &b{target}&3, pistage désactivé dans le tracker &b{tracker}&3."
